create extension if not exists pgcrypto with schema extensions;

create schema if not exists app_private;
revoke all on schema app_private from anon, authenticated;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'account_type') then
    create type public.account_type as enum ('Étudiant', 'Formateur');
  end if;

  if not exists (select 1 from pg_type where typname = 'skill_level') then
    create type public.skill_level as enum ('Débutant', 'Intermédiaire', 'Avancé', 'Expert');
  end if;

  if not exists (select 1 from pg_type where typname = 'user_skill_role') then
    create type public.user_skill_role as enum ('Enseignant', 'Apprenant');
  end if;

  if not exists (select 1 from pg_type where typname = 'session_status') then
    create type public.session_status as enum ('Planifiée', 'En cours', 'Terminée', 'Annulée');
  end if;

  if not exists (select 1 from pg_type where typname = 'session_type') then
    create type public.session_type as enum ('Cours rapide', 'Atelier collectif', 'Club thématique');
  end if;

  if not exists (select 1 from pg_type where typname = 'contact_request_status') then
    create type public.contact_request_status as enum ('pending', 'accepted', 'rejected', 'cancelled');
  end if;
end $$;

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  account_type public.account_type not null default 'Étudiant',
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  email varchar(100) not null unique,
  bio text,
  avatar_url text,
  availabilities jsonb not null default '{}'::jsonb,
  experience_points integer not null default 0 check (experience_points >= 0),
  level integer not null default 1 check (level >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.skills (
  id bigint generated by default as identity primary key,
  name varchar(50) not null unique,
  category varchar(50) not null,
  created_at timestamptz not null default now()
);

create table public.user_skills (
  user_id uuid not null references public.users(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  role public.user_skill_role not null,
  level public.skill_level not null,
  created_at timestamptz not null default now(),
  primary key (user_id, skill_id)
);

create table public.sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  title varchar(100) not null,
  description text not null,
  type public.session_type not null,
  status public.session_status not null default 'Planifiée',
  scheduled_at timestamptz not null,
  location varchar(255) not null,
  max_participants integer not null default 1 check (max_participants > 0),
  host_id uuid not null references public.users(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.session_co_hosts (
  session_id uuid not null references public.sessions(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (session_id, user_id)
);

create table public.session_registrations (
  session_id uuid not null references public.sessions(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  registered_at timestamptz not null default now(),
  primary key (session_id, user_id)
);

create table public.badges (
  id bigint generated by default as identity primary key,
  title varchar(50) not null unique,
  description varchar(255) not null,
  icon_url varchar(255) not null,
  created_at timestamptz not null default now()
);

create table public.user_badges (
  user_id uuid not null references public.users(id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, badge_id)
);

create table public.feedbacks (
  id uuid primary key default extensions.gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete cascade,
  receiver_id uuid not null references public.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  constraint feedbacks_sender_receiver_distinct check (sender_id <> receiver_id)
);

create table public.contact_requests (
  id uuid primary key default extensions.gen_random_uuid(),
  sender_user_id uuid not null references public.users(id) on delete cascade,
  receiver_user_id uuid not null references public.users(id) on delete cascade,
  status public.contact_request_status not null default 'pending',
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint contact_requests_sender_receiver_distinct check (sender_user_id <> receiver_user_id)
);

create table public.user_contacts (
  user_id uuid not null references public.users(id) on delete cascade,
  contact_user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, contact_user_id),
  constraint user_contacts_distinct_users check (user_id <> contact_user_id)
);

create table public.user_blocks (
  blocker_user_id uuid not null references public.users(id) on delete cascade,
  blocked_user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_user_id, blocked_user_id),
  constraint user_blocks_distinct_users check (blocker_user_id <> blocked_user_id)
);

create table public.conversations (
  id uuid primary key default extensions.gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table public.conversation_participants (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table public.messages (
  id uuid primary key default extensions.gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_user_id uuid not null references public.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  is_deleted boolean not null default false
);

create unique index contact_requests_one_pending_per_pair
  on public.contact_requests (
    least(sender_user_id, receiver_user_id),
    greatest(sender_user_id, receiver_user_id)
  )
  where status = 'pending';

create index user_skills_skill_id_idx on public.user_skills(skill_id);
create index sessions_host_id_idx on public.sessions(host_id);
create index sessions_skill_id_idx on public.sessions(skill_id);
create index sessions_scheduled_at_idx on public.sessions(scheduled_at);
create index session_registrations_user_id_idx on public.session_registrations(user_id);
create index session_co_hosts_user_id_idx on public.session_co_hosts(user_id);
create index feedbacks_session_id_idx on public.feedbacks(session_id);
create index feedbacks_receiver_id_idx on public.feedbacks(receiver_id);
create index contact_requests_receiver_user_id_idx on public.contact_requests(receiver_user_id);
create index user_contacts_contact_user_id_idx on public.user_contacts(contact_user_id);
create index messages_conversation_id_created_at_idx on public.messages(conversation_id, created_at desc);
create index conversation_participants_user_id_idx on public.conversation_participants(user_id);

create or replace function app_private.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger set_users_updated_at
  before update on public.users
  for each row execute function app_private.set_updated_at();

create trigger set_sessions_updated_at
  before update on public.sessions
  for each row execute function app_private.set_updated_at();

create or replace function app_private.skill_swap_level_for_experience(total_experience integer)
returns integer
language plpgsql
immutable
as $$
declare
  remaining_experience integer := greatest(coalesce(total_experience, 0), 0);
  computed_level integer := 1;
  required_experience integer := 500;
begin
  while remaining_experience >= required_experience loop
    remaining_experience := remaining_experience - required_experience;
    computed_level := computed_level + 1;
    required_experience := computed_level * 500;
  end loop;

  return computed_level;
end;
$$;

create or replace function app_private.sync_user_level_from_experience()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.experience_points := greatest(coalesce(new.experience_points, 0), 0);
  new.level := app_private.skill_swap_level_for_experience(new.experience_points);

  return new;
end;
$$;

create trigger sync_user_level_from_experience
  before insert or update of experience_points on public.users
  for each row execute function app_private.sync_user_level_from_experience();

create or replace function app_private.prevent_blocked_contact_request()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (
    select 1
    from public.user_blocks
    where (blocker_user_id = new.sender_user_id and blocked_user_id = new.receiver_user_id)
       or (blocker_user_id = new.receiver_user_id and blocked_user_id = new.sender_user_id)
  ) then
    raise exception 'Cannot create a contact request between blocked users.';
  end if;

  return new;
end;
$$;

create trigger prevent_blocked_contact_request
  before insert on public.contact_requests
  for each row execute function app_private.prevent_blocked_contact_request();

create or replace function app_private.create_contacts_after_request_acceptance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'accepted' and old.status <> 'accepted' then
    insert into public.user_contacts (user_id, contact_user_id)
    values
      (new.sender_user_id, new.receiver_user_id),
      (new.receiver_user_id, new.sender_user_id)
    on conflict (user_id, contact_user_id) do nothing;

    new.responded_at := coalesce(new.responded_at, now());
  end if;

  return new;
end;
$$;

create trigger create_contacts_after_request_acceptance
  before update of status on public.contact_requests
  for each row execute function app_private.create_contacts_after_request_acceptance();

create or replace function app_private.remove_contacts_after_block()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.user_contacts
  where (user_id = new.blocker_user_id and contact_user_id = new.blocked_user_id)
     or (user_id = new.blocked_user_id and contact_user_id = new.blocker_user_id);

  return new;
end;
$$;

create trigger remove_contacts_after_block
  after insert on public.user_blocks
  for each row execute function app_private.remove_contacts_after_block();

create or replace function app_private.validate_session_co_host()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (
    select 1
    from public.sessions
    where id = new.session_id
      and host_id = new.user_id
  ) then
    raise exception 'Session host cannot also be co-host.';
  end if;

  if not exists (
    select 1
    from public.users
    where id = new.user_id
      and account_type = 'Formateur'
  ) then
    raise exception 'Only trainers can join a session as co-host.';
  end if;

  if exists (
    select 1
    from public.session_registrations
    where session_id = new.session_id
      and user_id = new.user_id
  ) then
    raise exception 'A co-host cannot also be registered as learner.';
  end if;

  return new;
end;
$$;

create trigger validate_session_co_host
  before insert or update on public.session_co_hosts
  for each row execute function app_private.validate_session_co_host();

create or replace function app_private.validate_session_registration()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  participant_count integer;
  participant_limit integer;
begin
  if exists (
    select 1
    from public.sessions
    where id = new.session_id
      and host_id = new.user_id
  ) then
    raise exception 'Session host cannot register as learner.';
  end if;

  if exists (
    select 1
    from public.session_co_hosts
    where session_id = new.session_id
      and user_id = new.user_id
  ) then
    raise exception 'Session co-host cannot register as learner.';
  end if;

  select count(sr.user_id), s.max_participants
  into participant_count, participant_limit
  from public.sessions s
  left join public.session_registrations sr on sr.session_id = s.id
  where s.id = new.session_id
  group by s.max_participants;

  if participant_count >= participant_limit then
    raise exception 'Session is full.';
  end if;

  return new;
end;
$$;

create trigger validate_session_registration
  before insert or update on public.session_registrations
  for each row execute function app_private.validate_session_registration();

create or replace function app_private.validate_message_sender()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.conversation_participants
    where conversation_id = new.conversation_id
      and user_id = new.sender_user_id
  ) then
    raise exception 'Message sender must belong to the conversation.';
  end if;

  if exists (
    select 1
    from public.conversation_participants other_participant
    join public.user_blocks blocks
      on (blocks.blocker_user_id = new.sender_user_id and blocks.blocked_user_id = other_participant.user_id)
      or (blocks.blocker_user_id = other_participant.user_id and blocks.blocked_user_id = new.sender_user_id)
    where other_participant.conversation_id = new.conversation_id
      and other_participant.user_id <> new.sender_user_id
  ) then
    raise exception 'Cannot send a message to a blocked user.';
  end if;

  return new;
end;
$$;

create trigger validate_message_sender
  before insert on public.messages
  for each row execute function app_private.validate_message_sender();

create or replace function app_private.is_conversation_participant(
  target_conversation_id uuid,
  target_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversation_participants
    where conversation_id = target_conversation_id
      and user_id = target_user_id
  );
$$;

revoke execute on all functions in schema app_private from public;
grant usage on schema app_private to authenticated;
grant execute on function app_private.is_conversation_participant(uuid, uuid) to authenticated;

alter table public.users enable row level security;
alter table public.skills enable row level security;
alter table public.user_skills enable row level security;
alter table public.sessions enable row level security;
alter table public.session_co_hosts enable row level security;
alter table public.session_registrations enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;
alter table public.feedbacks enable row level security;
alter table public.contact_requests enable row level security;
alter table public.user_contacts enable row level security;
alter table public.user_blocks enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;

create policy "users_select_authenticated"
  on public.users for select
  to authenticated
  using (true);

create policy "users_insert_own"
  on public.users for insert
  to authenticated
  with check (id = (select auth.uid()));

create policy "users_update_own"
  on public.users for update
  to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

create policy "skills_select_authenticated"
  on public.skills for select
  to authenticated
  using (true);

create policy "user_skills_select_authenticated"
  on public.user_skills for select
  to authenticated
  using (true);

create policy "user_skills_manage_own"
  on public.user_skills for all
  to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "sessions_select_authenticated"
  on public.sessions for select
  to authenticated
  using (true);

create policy "sessions_insert_own_host"
  on public.sessions for insert
  to authenticated
  with check (host_id = (select auth.uid()));

create policy "sessions_update_own_host"
  on public.sessions for update
  to authenticated
  using (host_id = (select auth.uid()))
  with check (host_id = (select auth.uid()));

create policy "session_co_hosts_select_authenticated"
  on public.session_co_hosts for select
  to authenticated
  using (true);

create policy "session_co_hosts_insert_own"
  on public.session_co_hosts for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy "session_co_hosts_delete_own"
  on public.session_co_hosts for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "session_registrations_select_authenticated"
  on public.session_registrations for select
  to authenticated
  using (true);

create policy "session_registrations_insert_own"
  on public.session_registrations for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy "session_registrations_delete_own"
  on public.session_registrations for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "badges_select_authenticated"
  on public.badges for select
  to authenticated
  using (true);

create policy "user_badges_select_authenticated"
  on public.user_badges for select
  to authenticated
  using (true);

create policy "feedbacks_select_session_members"
  on public.feedbacks for select
  to authenticated
  using (
    sender_id = (select auth.uid())
    or receiver_id = (select auth.uid())
    or exists (
      select 1
      from public.sessions
      where sessions.id = feedbacks.session_id
        and sessions.host_id = (select auth.uid())
    )
  );

create policy "feedbacks_insert_own"
  on public.feedbacks for insert
  to authenticated
  with check (sender_id = (select auth.uid()));

create policy "contact_requests_select_involved"
  on public.contact_requests for select
  to authenticated
  using (
    sender_user_id = (select auth.uid())
    or receiver_user_id = (select auth.uid())
  );

create policy "contact_requests_insert_own"
  on public.contact_requests for insert
  to authenticated
  with check (sender_user_id = (select auth.uid()));

create policy "contact_requests_update_receiver"
  on public.contact_requests for update
  to authenticated
  using (receiver_user_id = (select auth.uid()))
  with check (receiver_user_id = (select auth.uid()));

create policy "user_contacts_select_own"
  on public.user_contacts for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "user_contacts_delete_own"
  on public.user_contacts for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "user_blocks_select_own"
  on public.user_blocks for select
  to authenticated
  using (blocker_user_id = (select auth.uid()));

create policy "user_blocks_insert_own"
  on public.user_blocks for insert
  to authenticated
  with check (blocker_user_id = (select auth.uid()));

create policy "user_blocks_delete_own"
  on public.user_blocks for delete
  to authenticated
  using (blocker_user_id = (select auth.uid()));

create policy "conversations_select_participants"
  on public.conversations for select
  to authenticated
  using (app_private.is_conversation_participant(id, (select auth.uid())));

create policy "conversations_insert_authenticated"
  on public.conversations for insert
  to authenticated
  with check (true);

create policy "conversation_participants_select_self_conversations"
  on public.conversation_participants for select
  to authenticated
  using (app_private.is_conversation_participant(conversation_id, (select auth.uid())));

create policy "conversation_participants_insert_self_or_existing_participant"
  on public.conversation_participants for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    or app_private.is_conversation_participant(conversation_id, (select auth.uid()))
  );

create policy "messages_select_participants"
  on public.messages for select
  to authenticated
  using (app_private.is_conversation_participant(conversation_id, (select auth.uid())));

create policy "messages_insert_participant"
  on public.messages for insert
  to authenticated
  with check (sender_user_id = (select auth.uid()));

grant usage on schema public to anon, authenticated;
grant select on public.skills to anon, authenticated;
grant all on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

comment on table public.users is 'SkillSwap public profiles linked to Supabase Auth users.';
comment on column public.users.experience_points is 'Cumulative SkillSwap XP used for level progression.';
comment on column public.users.level is 'Public SkillSwap level. The next level requires current level * 500 additional XP.';
