import {
  addCircleOutline,
  addOutline,
  arrowBackOutline,
  arrowForwardOutline,
  barChartOutline,
  bookOutline,
  calendarOutline,
  chatboxEllipsesOutline,
  chatboxOutline,
  chatbubblesOutline,
  checkmarkCircleOutline,
  chevronDownOutline,
  closeOutline,
  codeSlashOutline,
  colorPaletteOutline,
  compassOutline,
  createOutline,
  documentTextOutline,
  helpOutline,
  homeOutline,
  imageOutline,
  informationCircleOutline,
  languageOutline,
  libraryOutline,
  locationOutline,
  lockClosedOutline,
  logoPython,
  logoReact,
  mailOutline,
  micOutline,
  moonOutline,
  notificationsOffOutline,
  notificationsOutline,
  peopleCircleOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  personOutline,
  powerOutline,
  reloadOutline,
  ribbonOutline,
  rocketOutline,
  sadOutline,
  schoolOutline,
  searchCircleOutline,
  searchOutline,
  sendOutline,
  settingsOutline,
  shareSocialOutline,
  shieldCheckmarkOutline,
  sparklesOutline,
  starOutline,
  sunnyOutline,
  timeOutline,
  trashOutline,
  trophyOutline,
} from 'ionicons/icons'

/** Kebab-case name → bundled SVG data URL (works in production without web components). */
export const iconSources: Record<string, string> = {
  'add-circle-outline': addCircleOutline,
  'add-outline': addOutline,
  'arrow-back-outline': arrowBackOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'bar-chart-outline': barChartOutline,
  'book-outline': bookOutline,
  'calendar-outline': calendarOutline,
  'chatbox-ellipses-outline': chatboxEllipsesOutline,
  'chatbox-outline': chatboxOutline,
  'chatbubbles-outline': chatbubblesOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'chevron-down-outline': chevronDownOutline,
  'close-outline': closeOutline,
  'code-slash-outline': codeSlashOutline,
  'color-palette-outline': colorPaletteOutline,
  'compass-outline': compassOutline,
  'create-outline': createOutline,
  'document-text-outline': documentTextOutline,
  'help-outline': helpOutline,
  'home-outline': homeOutline,
  'image-outline': imageOutline,
  'information-circle-outline': informationCircleOutline,
  'language-outline': languageOutline,
  'library-outline': libraryOutline,
  'location-outline': locationOutline,
  'lock-closed-outline': lockClosedOutline,
  'logo-python': logoPython,
  'logo-react': logoReact,
  'mail-outline': mailOutline,
  'mic-outline': micOutline,
  'moon-outline': moonOutline,
  'notifications-off-outline': notificationsOffOutline,
  'notifications-outline': notificationsOutline,
  'people-circle-outline': peopleCircleOutline,
  'people-outline': peopleOutline,
  'person-add-outline': personAddOutline,
  'person-circle-outline': personCircleOutline,
  'person-outline': personOutline,
  'power-outline': powerOutline,
  'reload-outline': reloadOutline,
  'ribbon-outline': ribbonOutline,
  'rocket-outline': rocketOutline,
  'sad-outline': sadOutline,
  'school-outline': schoolOutline,
  'search-circle-outline': searchCircleOutline,
  'search-outline': searchOutline,
  'send-outline': sendOutline,
  'settings-outline': settingsOutline,
  'share-social-outline': shareSocialOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'sparkles-outline': sparklesOutline,
  'star-outline': starOutline,
  'sunny-outline': sunnyOutline,
  'time-outline': timeOutline,
  'trash-outline': trashOutline,
  'trophy-outline': trophyOutline,
}
